<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>数字产品网站</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f9f4;
            color: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            flex-direction: column;
        }

        h1 {
            font-size: 24px;
            margin-bottom: 30px;
            color: #2C3E50;
        }

        .button-container {
            display: flex;
            gap: 20px;
        }

        button {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 15px 25px;
            text-align: center;
            text-decoration: none;
            font-size: 18px;
            cursor: pointer;
            border-radius: 10px;
            transition: background-color 0.3s, transform 0.2s;
        }

        button:hover {
            background-color: #45a049;
            transform: translateY(-5px);
        }

        button:active {
            background-color: #388e3c;
            transform: translateY(0);
        }

        .hidden {
            display: none;
        }

        .options-container {
            margin-top: 20px;
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        .options-container button {
            background-color: #3498db;
        }

        .options-container button:hover {
            background-color: #2980b9;
        }

        /* 响应式设计 */
        @media (max-width: 600px) {
            .button-container {
                flex-direction: column;
                gap: 15px;
            }
        }
    </style>
</head>
<body>

    <h1>选择数字产品</h1>

    <div class="button-container">
        <!-- 两个主按钮 -->
        <button id="btnPhone" onclick="showPhoneOptions()">手机</button>
        <button id="btnCamera" onclick="showCameraOptions()">相机</button>
    </div>

    <!-- 手机选项按钮 -->
    <div id="phoneOptions" class="options-container hidden">
        <button onclick="window.location.href='https://www.wmslz.com/s/tQmuN2O81rI#'">鸿创数码</button>
        <button onclick="window.location.href='https://www.wmslz.com/s/ybQctUv81nT#'">品正数码</button>
    </div>

    <!-- 相机选项按钮 -->
    <div id="cameraOptions" class="options-container hidden">
        <button onclick="window.location.href='https://www.wmslz.com/s/tQmuN2O81rI#'">赁品数码</button>
    </div>

    <script>
        // 显示手机选项
        function showPhoneOptions() {
            document.getElementById('phoneOptions').classList.remove('hidden');
            document.getElementById('cameraOptions').classList.add('hidden');
        }

        // 显示相机选项
        function showCameraOptions() {
            document.getElementById('cameraOptions').classList.remove('hidden');
            document.getElementById('phoneOptions').classList.add('hidden');
        }
    </script>

</body>
</html>

